name: React Frontend Tests

on: [push, pull_request]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017

    env:
      MONGODB_CONNECTION: mongodb://mongo:27017/Pharmachy_Dashboard
      HTTP_PROXY: ''
      HTTPS_PROXY: ''

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node for Backend
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        working-directory: Backend
        run: npm install

      - name: Start Backend
        working-directory: Backend
        run: |
          npm start &
          echo "Waiting for backend to be ready..."
          for i in {1..20}; do
            if curl --silent http://localhost:5000/; then
              echo "✅ Backend is up!"
              break
            else
              echo "⏳ Still waiting for backend..."
              sleep 3
            fi
          done

      - name: Setup Node for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: Frontend
        run: npm install --ignore-scripts

      - name: Run Frontend Tests
        working-directory: Frontend
        run: npm test -- --watchAll=false
