name: React Frontend Tests

on: [push, pull_request]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Cache backend dependencies
      - name: Cache Backend Dependencies
        uses: actions/cache@v3
        with:
          path: Backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('Backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Setup Node.js (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        working-directory: Backend
        run: npm ci

      # Ensure port 5000 is free before starting backend
      - name: Release port 5000 if occupied
        run: |
          if lsof -i :5000 > /dev/null; then
            echo "Port 5000 is occupied, terminating process..."
            lsof -t -i :5000 | xargs kill -9 || true
          else
            echo "Port 5000 is free"
          fi

      # Start backend and wait until it's ready
      - name: Launch Backend and Await Availability
        working-directory: Backend
        run: |
          nohup npm start > backend.log 2>&1 &
          echo "Waiting for backend to be accessible on port 5000..."
          for i in {1..30}; do
            if curl --silent http://localhost:5000/ > /dev/null; then
              echo "Backend is up and running!"
              exit 0
            fi
            echo "Waiting for backend... (attempt $i)"
            sleep 3
          done
          echo "Backend failed to start within expected time. Logs:"
          cat backend.log
          exit 1

      # Cache frontend dependencies
      - name: Cache Frontend Dependencies
        uses: actions/cache@v3
        with:
          path: Frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('Frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: Frontend
        run: npm ci

      - name: Run Frontend Tests
        working-directory: Frontend
        run: npm test -- --watchAll=false

      # Stop backend process after tests complete
      - name: Terminate Backend Process
        run: |
          pkill -f "node app.js" || echo "No backend process found to kill"
