name: React Frontend Tests

on: [push, pull_request]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Cache backend deps
      - name: Cache backend dependencies
        uses: actions/cache@v3
        with:
          path: Backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('Backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Setup Node for Backend
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Backend Dependencies
        working-directory: Backend
        run: npm ci

      # Free port 5000 if busy before starting backend
      - name: Free port 5000 if busy
        run: |
          if lsof -i :5000; then
            echo "Port 5000 is busy, killing process"
            lsof -t -i :5000 | xargs kill -9
          else
            echo "Port 5000 is free"
          fi

      # Start backend and wait for it to be ready
      - name: Start Backend and wait
        working-directory: Backend
        run: |
          npm start &           # start backend in background
          sleep 5               # wait a few seconds before polling
          n=0
          until curl --silent http://localhost:5000/ || [ $n -eq 30 ]; do
            echo "Waiting for backend to be ready..."
            sleep 3
            n=$((n+1))
          done
          if [ $n -eq 30 ]; then
            echo "Backend failed to start"
            exit 1
          fi
          echo "Backend is ready!"

      # Cache frontend deps
      - name: Cache frontend dependencies
        uses: actions/cache@v3
        with:
          path: Frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('Frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Setup Node for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: Frontend
        run: npm ci

      - name: Run Frontend Tests
        working-directory: Frontend
        run: npm test -- --watchAll=false
