name: React Frontend Tests

on: [push, pull_request]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v3

      - name: Setup Backend
        working-directory: Backend
        env:
          MONGODB_CONNECTION: mongodb://mongo:27017/Pharmachy_Dashboard
        run: |
          npm install
          npm start &

      - name: Wait for backend to be ready
        run: sleep 10

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: Frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: Frontend
        run: npm test -- --watchAll=false
